name: Update jakarta branch

on:
  push:
    branches:
      - master

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        - with:
            ref: jakarta

      - name: Reset promotion branch
          run: |
            git fetch origin master:master
            git reset --hard master

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          commit-message: ${{ github.event.head_commit.message }}
          title: ${{ github.event.head_commit.message }}
          branch: jakarta-test
