name: Update jakarta branch

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate new branch name
        run: |
          echo "::set-output name=branch_name::new-branch-$(date +%s)"
        id: branch_name
      - name: Fetch branch
        run: git fetch origin jakarta:jakarta master
      - name: Create new branch
        run: git checkout -b ${{ steps.branch_name.outputs.branch_name }} jakarta
      - name: Add commit to new branch
        run: git reset --hard origin/master
      - name: Build project
        run: mvn clean install
      - name: Merge branch into jakarta
        if: success()
        run: |
          git push origin ${{ steps.branch_name.outputs.branch_name }}
          git checkout jakarta
          git merge ${{ steps.branch_name.outputs.branch_name }} --no-commit --no-ff
          git commit -m "Merge ${{ steps.branch_name.outputs.branch_name }} into jakarta"
          git push origin jakarta
#      - name: Delete new branch
#        run: git branch -d ${{ steps.branch_name.outputs.branch_name }}
